services:
  - type: worker
    name: snarkels-polling-service
    env: node
    buildCommand: npm install
    startCommand: node scripts/start-polling-service.js
    envVars:
      - key: ENABLE_POLLING
        value: true
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_PREDICTION_MARKET_ADDRESS_CELO
        value: 0x7176D16D61A122231a78749c61740ad8F86BB13a
      - key: NEXT_PUBLIC_PREDICTION_MARKET_CLAIMS_ADDRESS_CELO
        value: 0x1e1ac759e75dA03a39f16ae72B73279A1edf63d6
      # Note: You'll need to set these in Render dashboard:
      # - NEXT_PUBLIC_SUPABASE_URL
      # - NEXT_PUBLIC_SUPABASE_ANON_KEY